version: 0.1.{build}
image:
- Visual Studio 2017
- Ubuntu
install:
  - cmd: powershell Install-Product node 6
  - sh: nvm install 6
before_build:
- nuget restore
- ps: |
    cd PetGame
    npm install gulp-cli --global
    npm install
    gulp default  
build:
  publish_aspnet_core: true
  verbosity: minimal
