version: 0.1.{build}
image:
- Visual Studio 2017
- Ubuntu
before_build:
- nuget restore
- pwsh: >-
    cd PetGame

    npm install

    gulp default  
build:
  publish_aspnet_core: true
  verbosity: minimal